userCREATE TABLE `user`(
	`id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `email` VARCHAR(64) NOT NULL,
    `realName` VARCHAR(32) NOT NULL,
    `nickName` VARCHAR(32) NOT NULL,
    `password` VARCHAR(32) NOT NULL,
    `createdAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updatedAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)  ENGINE=INNODB DEFAULT CHARSET=UTF8MB4;

DROP TABLE `user`;