CREATE TABLE `user`(
	`id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `email` VARCHAR(64) NOT NULL,
    `realName` VARCHAR(32) NOT NULL,
    `nickName` VARCHAR(32) NOT NULL,
    `password` VARCHAR(32) NOT NULL,
    `createdAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updatedAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)  ENGINE=INNODB DEFAULT CHARSET=UTF8MB4;



SELECT * FROM `user`;

CREATE TABLE `post`(
	`id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `userId` INT NOT NULL,
    `contents` TEXT NOT NULL,
    `imagePath` VARCHAR(128) NOT NULL,
    `musicId` INT,
    `createdAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updatedAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)ENGINE=INNODB DEFAULT CHARSET=UTF8MB4;


SELECT * FROM `post`;

CREATE TABLE `profile`(
	`id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `userId`INT NOT NULL,
    `introduce` VARCHAR(128),
    `profileImagePath` VARCHAR(128),
    `createdAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updatedAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)  ENGINE=INNODB DEFAULT CHARSET=UTF8MB4;
SELECT * FROM `profile`;



CREATE TABLE `like`(
	`id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `userId`INT NOT NULL,
    `postId`INT NOT NULL,
    `createdAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)  ENGINE=INNODB DEFAULT CHARSET=UTF8MB4;

select * from `like` where `userId`=2 and `postId`=3;

SELECT * FROM `like`;


select count(*) from `like`  where `postId`=1;


CREATE TABLE `comments`(
	`id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `userId`INT NOT NULL,
    `postId`INT NOT NULL,
    `comment` VARCHAR(128) NOT NULL,
    `createdAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updatedAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)  ENGINE=INNODB DEFAULT CHARSET=UTF8MB4;

SELECT * FROM `comments`;


