CREATE TABLE `user` (
    `id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `loginId` VARCHAR(16) NOT NULL,
    `password` VARCHAR(32) NOT NULL,
    `name` VARCHAR(16) NOT NULL,
    `email` VARCHAR(64) NOT NULL,
    `createdAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updatedAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)  ENGINE=INNODB DEFAULT CHARSET=UTF8MB4; 
SELECT * FROM `user`;
DROP TABLE `user`;

CREATE TABLE `post` (
    `id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `userId` INT NOT NULL,
    `title` VARCHAR(64) NOT NULL,
    `contents` TEXT NOT NULL,
    `imagePath` VARCHAR(128) NULL,
    `createdAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updatedAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)  ENGINE=INNODB DEFAULT CHARSET=UTF8MB4;

SELECT * FROM `post`;
DROP TABLE `post`;