CREATE TABLE `user` (
    `id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `loginId` VARCHAR(16) NOT NULL,
    `password` VARCHAR(32) NOT NULL,
    `name` VARCHAR(16) NOT NULL,
    `email` VARCHAR(64) NOT NULL,
    `createdAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updatedAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)  ENGINE=INNODB DEFAULT CHARSET=UTF8MB4; 
SELECT * FROM `user`;